kaiko-ai/eva

- .github/workflows/docs.yaml
- mkdocs.yml
- noxfile.py
- pdm.lock
- pyproject.toml
> Create a developer docs workflow

- src/eva/vision/data/datasets/_validators.py
- src/eva/vision/data/datasets/classification/bach.py
- src/eva/vision/data/datasets/classification/crc.py
- src/eva/vision/data/datasets/classification/mhist.py
- src/eva/vision/data/datasets/classification/patch_camelyon.py
- src/eva/vision/data/datasets/classification/total_segmentator.py
> Add check if dataset exists

- .github/workflows/ci.yaml
- docs/CODE_OF_CONDUCT.md
> Update email in CoC

- configs/vision/dino_vit/offline/bach.yaml
- pdm.lock
- pyproject.toml
- src/eva/core/trainers/_recorder.py
- src/eva/core/trainers/functional.py
- src/eva/core/trainers/trainer.py
> Print results table at the end of an evaluation session

- docs/reference/core/data/datasets.md
- docs/reference/core/data/transforms.md
- mkdocs.yml
- src/eva/core/data/datasets/__init__.py
- src/eva/core/data/datasets/classification/__init__.py
- src/eva/core/data/datasets/embeddings/__init__.py
- src/eva/core/data/datasets/embeddings/base.py
- src/eva/core/data/datasets/embeddings/classification/__init__.py
- src/eva/core/data/datasets/embeddings/classification/embeddings.py
- src/eva/core/data/datasets/embeddings/classification/multi_embeddings.py
- src/eva/core/data/transforms/__init__.py
- src/eva/core/data/transforms/padding/__init__.py
- src/eva/core/data/transforms/padding/pad_2d_tensor.py
- src/eva/core/data/transforms/sampling/__init__.py
- src/eva/core/data/transforms/sampling/sample_from_axis.py
- tests/eva/core/data/datasets/classification/__init__.py
- tests/eva/core/data/datasets/classification/test_embedding_datasets.py
- tests/eva/core/data/datasets/embeddings/__init__.py
- tests/eva/core/data/datasets/embeddings/classification/__init__.py
- tests/eva/core/data/datasets/embeddings/classification/test_embeddings.py
- tests/eva/core/data/datasets/embeddings/classification/test_multi_embeddings.py
- tests/eva/core/data/transforms/__init__.py
- tests/eva/core/data/transforms/padding/__init__.py
- tests/eva/core/data/transforms/padding/test_pad_2d_tensor.py
- tests/eva/core/data/transforms/sampling/__init__.py
- tests/eva/core/data/transforms/sampling/test_sample_from_axis.py
Closes #350 
- Refactors embedding dataset classes
- Add a new `MultiEmbeddingsClassificationDataset` to support slide level tasks
- The class is written in a way that is agnostic to WSIs
- The transformations `SampleFromAxis` and `Pad2DTensor` are included in this PR, because they are needed for common MIL setups in slide level tasks (e.g. our abmil implementation expects padded tensors of shape `(batch_size, n_instances, input_size)`)
> Add `MultiEmbeddingsClassificationDataset`

- docs/reference/core/data/datasets.md
- docs/reference/core/loggers/loggers.md
- mkdocs.yml
- src/eva/core/loggers/__init__.py
- src/eva/core/loggers/dummy.py
- src/eva/core/trainers/_logging.py
- src/eva/core/trainers/trainer.py
Closes #338 
If `OUTPUT_ROOT` is set to a remote path and the config file lists loggers that don't support remote storage, the loggers will be disabled at runtime and a warning will be displayed:
With that change, we can now store the evaluation results directly to remote storage.
> Disable Loggers that don't support saving to remote storage at runtime

- src/eva/vision/data/wsi/__init__.py
- src/eva/vision/data/wsi/backend.py
- src/eva/vision/data/wsi/base.py
- src/eva/vision/data/wsi/openslide.py
> Add base class for WSIs & `openslide` implementation

- src/eva/vision/data/datasets/wsi.py
- src/eva/vision/data/wsi/__init__.py
- src/eva/vision/data/wsi/backends/__init__.py
- src/eva/vision/data/wsi/patching/coordinates.py
Closes #387 
Tested using 10k WSIs with 100 patches each using a dataloader with 10 workers. With this fix the memory doesn't build up anymore:
> Replace `cached_property` in `WsiDataset` by LRU cache

- configs/vision/dino_vit/offline/panda.yaml
- src/eva/core/callbacks/writers/embeddings.py
- src/eva/core/callbacks/writers/typings.py
- tests/eva/core/callbacks/writers/test_embeddings.py
Closes #376 
- Implemented support for adding multiple embeddings to the same `.pt` if they share the same filename (e.g. slide_id)
- Made `EmbeddingsWriter` agnostic to WSI's by replacing slide_id field extraction by generic `metadata_keys`
- Refactored & updated unit tests
This helps to prevent the explosion of the number of files for slide level tasks, where you can have thousands of patch embeddings per slide. Each slide now results in a single `.pt` file of shape `[n_patches, embedding_dim]`.
> Updated `EmbeddingsWriter` to support multi-embedding file outputs

- src/eva/vision/data/datasets/_utils.py
- src/eva/vision/data/datasets/segmentation/total_segmentator.py
- tests/eva/vision/data/datasets/segmentation/test_total_segmentator.py
> Update `TotalSegmentator2D` dataset to fetch all the slices

- src/eva/vision/data/wsi/backends/openslide.py
closes https://github.com/kaiko-ai/eva/issues/426
> Retrieve MPP from WSIs 

- src/eva/vision/data/wsi/__init__.py
- src/eva/vision/data/wsi/patching/mask.py
- tests/eva/vision/data/wsi/patching/test_mask.py
Closes #455
I used a simplified version of the segmentation algorithm from [CLAM](https://github.com/mahmoodlab/CLAM). CLAM on top of what is implemented here filters the approximate contours of the detected foreground objects based on an area threshold as a post processing step. We don't need this step here, because our patching logic anyways applies another foreground threshold filter to the sampled patches, so very small foreground areas in the mask most likely won't yield patches anyways. 
- "grayscale-threshold" is what we've been using so far (for datasets such as panda which have a clean white background this worked reasonably well, but it breaks for datasets such as camelyon16 where this is not the case)
- mb stands for median blur applied to saturation channel in HSV image
- otsu …
> Update WSI foreground segmentation algorithm

- configs/vision/dino_vit/offline/camelyon16.yaml
- configs/vision/dino_vit/offline/panda.yaml
- configs/vision/owkin/phikon/offline/camelyon16.yaml
- configs/vision/owkin/phikon/offline/panda.yaml
- tests/eva/vision/test_vision_cli.py
closes https://github.com/kaiko-ai/eva/issues/475 (see protocol details in issue)
> 475 define slide level evaluation protocol

- configs/vision/dino_vit/offline/camelyon16.yaml
- configs/vision/owkin/phikon/offline/camelyon16.yaml
closes https://github.com/kaiko-ai/eva/issues/537
Note: memory still builds up during predict and accumulates across dataloaders/splits. However, ray node does not crash anymore with example camelyon16/phikon
> updated camelyon16 configs to save embeddings less frequent

- configs/vision/dino_vit/offline/bach.yaml
- configs/vision/dino_vit/offline/camelyon16.yaml
- configs/vision/dino_vit/offline/crc.yaml
- configs/vision/dino_vit/offline/mhist.yaml
- configs/vision/dino_vit/offline/panda.yaml
- configs/vision/dino_vit/offline/patch_camelyon.yaml
- src/eva/core/callbacks/writers/embeddings/_manifest.py
- src/eva/core/callbacks/writers/embeddings/base.py
- tests/eva/core/callbacks/writers/embeddings/test_classification.py
Closes #557 
Enabling overwriting embeddings by default is risky, as users might unintentionally overwrite previously computed embeddings.
> Change `overwrite` default value to True in `EmbeddingWriter`

- src/eva/core/data/datasets/embeddings.py
Closes #620
On local machine (macOS) it was working because there the default start method is set to `spawn`, while on the linux machine where the error occured default used by `torch.DataLoader` was `fork` (If you don't specify `multiprocessing_context` expliclitly when initializing a `DataLoader` it will use the OS default).
Using `fork` can be unsafe and lead to issues as deadlocks (see [context](https://stackoverflow.com/a/66113051)).
> Set multiprocessing start method to `spawn` for `EmbeddingsDataset`

- .gitignore
- src/eva/core/loggers/experimental_loggers.py
- src/eva/core/loggers/log/image.py
- src/eva/core/loggers/log/parameters.py
- src/eva/core/loggers/loggers.py
- src/eva/vision/callbacks/loggers/batch/segmentation.py
Closes #627
Example usage:
```yaml
logger:
- class_path: lightning.pytorch.loggers.WandbLogger
init_args:
project: ${oc.env:WANDB_PROJECT, eva}
name: ${oc.env:WANDB_RUN_NAME, ""}
```
> Add `WandbLogger`

- src/eva/vision/data/datasets/classification/camelyon16.py
Auto download is not available for `camelyon16`, but currently `check_dataset_exists` prints a message recommending setting the `DOWNLOAD_DATA` env variable.
> Set available auto download to `False` for `camelyon16`

- src/eva/core/models/wrappers/base.py
- src/eva/core/models/wrappers/from_function.py
- src/eva/core/models/wrappers/huggingface.py
- src/eva/core/models/wrappers/onnx.py
- src/eva/vision/models/wrappers/from_registry.py
- src/eva/vision/models/wrappers/from_timm.py
This refactoring ensures that all model wrapper classes derived from `BaseModel` will have a `_model` attribute which stores the instantiated model, and is used by default in the forward pass. (So far, each wrapper did this differently, some called it `_model`, others `_feature_extractor`, etc.)
> Refactoring of forward method in model wrapper classes

- configs/vision/pathology/offline/classification/camelyon16_small.yaml
closes https://github.com/kaiko-ai/eva/issues/663
Note: the only difference between `camelyon16.yaml` and `camelyon16_small.yaml` is `N_PATCHES`, which are 10,000 and 500 respectively. This number in `camelyon16_small.yaml` is experimental and parametrizable -- we will change the default subsequently if 500 turns out to be insufficient for meaningful benchmarking.
> Create a small version of the Camelyon16 dataset

- docs/user-guide/advanced/replicate_evaluations.md
Previously, we would omit values here in the commands when they matched the values from our default configs. I think it's more intuitive & safer to be explicit here.
> Mention mean, std and dim explicitly in `replicate_evaluations.md`

- src/eva/core/models/transforms/extract_patch_features.py
The [hibou](https://github.com/HistAI/hibou) models from [hist.ai](http://hist.ai/) use a vit architecture with 4 additional [register](https://arxiv.org/abs/2309.16588) tokens.
For segmentation tasks, we take the last feature map and reshape it to a 2D patch, so to do so the register tokens need to be skipped. In the current code, we seem to include the register tokens and instead skipping image tokens, which leads to poor performance.
See consep performance before & after this fix:
> Fix: Skip register tokens in `ExtractPatchFeatures`

- configs/vision/pathology/offline/segmentation/monusac.yaml
- configs/vision/pathology/online/segmentation/monusac.yaml
- src/eva/vision/data/datasets/segmentation/monusac.py
Monusac evaluation is not compatible with current metrics implementation:  
```
File "eva-worktrees/eva/src/eva/vision/metrics/segmentation/generalized_dice.py", line 56, in update
target = _utils.index_to_one_hot(target, num_classes=self.orig_num_classes)
File "eva-worktrees/eva/src/eva/vision/metrics/segmentation/_utils.py", line 48, in index_to_one_hot
tensor = torch.nn.functional.one_hot(tensor.long(), num_classes=num_classes).movedim(-1, 1)
RuntimeError: Class values must be smaller than num_classes.
```
The issue was that the `ambigous` class was mapped to a `255`, which is problematic when converting the target tensor to one-hot format.
> Update class indices in `MoNuSAC` to make compatible with generalized dice metric

- configs/vision/pathology/offline/classification/bach.yaml
- configs/vision/pathology/offline/classification/camelyon16.yaml
- configs/vision/pathology/offline/classification/camelyon16_small.yaml
- configs/vision/pathology/offline/classification/crc.yaml
- configs/vision/pathology/offline/classification/mhist.yaml
- configs/vision/pathology/offline/classification/panda.yaml
- configs/vision/pathology/offline/classification/panda_small.yaml
- configs/vision/pathology/offline/classification/patch_camelyon.yaml
- configs/vision/pathology/offline/segmentation/bcss.yaml
- configs/vision/pathology/offline/segmentation/consep.yaml
- configs/vision/pathology/offline/segmentation/monusac.yaml
- configs/vision/pathology/offline/segmentation/total_segmentator_2d.yaml
- configs/vision/pathology/online/classification/bach.yaml
- configs/vision/pathology/online/classification/crc.yaml
- configs/vision/pathology/online/classification/mhist.yaml
- configs/vision/pathology/online/classification/patch_camelyon.yaml
- configs/vision/pathology/online/segmentation/bcss.yaml
- configs/vision/pathology/online/segmentation/consep.yaml
- configs/vision/pathology/online/segmentation/monusac.yaml
- configs/vision/pathology/online/segmentation/total_segmentator_2d.yaml
- configs/vision/radiology/offline/segmentation/lits.yaml
- configs/vision/radiology/offline/segmentation/lits_balanced.yaml
- configs/vision/radiology/online/segmentation/lits.yaml
- configs/vision/radiology/online/segmentation/lits_balanced.yaml
- docs/user-guide/getting-started/how_to_use.md
- src/eva/core/data/dataloaders/dataloader.py
- src/eva/vision/data/datasets/segmentation/lits.py
Closes #679
Using a new default of 4 workers, as for most datapipelines speed doesn't seem to improve by increasing the worker count further.
> Add `N_DATA_WORKERS` env variable to make dataloader `num_workers` configurable

- docs/user-guide/getting-started/how_to_use.md
- src/eva/core/models/modules/module.py
Closes #677
Segmentation metrics calculation runs much faster on GPU - tested on `mps` and A100 gpu - Therefore the new default is to use the same device as for training for the metrics calculation.
> Make metrics device configurable through `METRICS_DEVICE` env variable

- src/eva/core/models/modules/module.py
For some reason, calculating the metrics on gpu gives random & invalid results. Setting the default back to `cpu` until we figure out why.
> Set default metrics device to cpu

- src/eva/core/models/modules/module.py
We found compatibility issues, particularly when calculating the segmentation metrics (e.g. `GeneralizedDice`) on `mps` (yields invalid / out of range or even negative numbers). This issue doesn't occur when running on `cuda` or `cpu`.
> Update `metrics_device` to use `cpu` when running on `mps`

- README.md
We now point to the leaderboard in the official docs, to avoid maintaining two independent sources.
> Remove leaderboard table from `README.md`

- docs/user-guide/advanced/replicate_evaluations.md
- src/eva/vision/models/networks/backbones/pathology/__init__.py
- src/eva/vision/models/networks/backbones/pathology/owkin.py
- src/eva/vision/models/networks/backbones/pathology/paige.py
> Add phikon-v2 to registry

- pdm.lock
- src/eva/core/models/wrappers/__init__.py
- src/eva/core/models/wrappers/from_torchhub.py
- src/eva/vision/models/networks/backbones/__init__.py
- src/eva/vision/models/networks/backbones/torchhub/__init__.py
- src/eva/vision/models/networks/backbones/torchhub/backbones.py
- src/eva/vision/models/networks/decoders/segmentation/decoder2d.py
- src/eva/vision/models/wrappers/__init__.py
- tests/eva/core/models/wrappers/test_from_torchub.py
> Add `TorchHubModel` model wrapper

- configs/vision/pathology/offline/classification/bach.yaml
- configs/vision/pathology/offline/classification/camelyon16.yaml
- configs/vision/pathology/offline/classification/camelyon16_small.yaml
- configs/vision/pathology/offline/classification/crc.yaml
- configs/vision/pathology/offline/classification/mhist.yaml
- configs/vision/pathology/offline/classification/panda.yaml
- configs/vision/pathology/offline/classification/panda_small.yaml
- configs/vision/pathology/offline/classification/patch_camelyon.yaml
- configs/vision/pathology/offline/segmentation/bcss.yaml
- configs/vision/pathology/offline/segmentation/consep.yaml
- configs/vision/pathology/offline/segmentation/monusac.yaml
- configs/vision/pathology/offline/segmentation/total_segmentator_2d.yaml
- configs/vision/pathology/online/classification/bach.yaml
- configs/vision/pathology/online/classification/crc.yaml
- configs/vision/pathology/online/classification/mhist.yaml
- configs/vision/pathology/online/classification/patch_camelyon.yaml
- configs/vision/pathology/online/segmentation/bcss.yaml
- configs/vision/pathology/online/segmentation/consep.yaml
- configs/vision/pathology/online/segmentation/monusac.yaml
- configs/vision/pathology/online/segmentation/total_segmentator_2d.yaml
- configs/vision/radiology/offline/segmentation/lits.yaml
- configs/vision/radiology/offline/segmentation/lits_balanced.yaml
- configs/vision/radiology/online/segmentation/lits.yaml
- configs/vision/radiology/online/segmentation/lits_balanced.yaml
- configs/vision/tests/offline/panda.yaml
- configs/vision/tests/offline/patch_camelyon.yaml
- configs/vision/tests/online/patch_camelyon.yaml
- docs/user-guide/getting-started/how_to_use.md
- src/eva/core/trainers/functional.py
- src/eva/core/trainers/trainer.py
Closes #725
- `CHECKPOINT_TYPE="best"` will select the best checkpoint saved during `fit`
- `CHECKPOINT_TYPE="last"` will select the last checkpoint saved during `fit`
> Add `CHECKPOINT_TYPE` env variable to configs

- configs/vision/pathology/offline/segmentation/bcss.yaml
- configs/vision/pathology/offline/segmentation/consep.yaml
- configs/vision/pathology/offline/segmentation/monusac.yaml
- configs/vision/pathology/online/segmentation/consep.yaml
- configs/vision/pathology/online/segmentation/monusac.yaml
- docs/leaderboards.md
- src/eva/core/models/__init__.py
- src/eva/core/models/wrappers/from_torchhub.py
- src/eva/vision/models/wrappers/from_timm.py
Turns out that `0.0001` is too low, leading to some evals not converging.
`0.002` seems to work well across all current models.
> Change learning rate for segmentation configs to `0.002`

- src/eva/core/models/modules/head.py
- src/eva/core/models/modules/utils/__init__.py
- src/eva/core/models/modules/utils/checkpoint.py
- src/eva/vision/models/modules/semantic_segmentation.py
> Override checkpointing hooks to exclude backbone while saving checkpoints

- configs/vision/pathology/online/segmentation/consep.yaml
By accident the `shuffle` argument for the train data loader of consep was set to `false` here:
https://github.com/kaiko-ai/eva/pull/719/
> Set shuffle option in train dataloader back to true in consep config

- tests/eva/vision/data/wsi/patching/samplers/test_foreground_grid.py
- tests/eva/vision/data/wsi/patching/samplers/test_random.py
The assert to check wether the values of the extracted coordinates match the expected values given a specific seed were missing.
> Add missing coordinate checks to sampler unit tests

- src/eva/core/models/wrappers/base.py
- src/eva/core/models/wrappers/from_function.py
- src/eva/core/models/wrappers/from_torchhub.py
- src/eva/core/models/wrappers/huggingface.py
- src/eva/core/models/wrappers/onnx.py
- src/eva/vision/models/networks/backbones/_utils.py
- src/eva/vision/models/networks/backbones/pathology/bioptimus.py
- src/eva/vision/models/networks/backbones/pathology/paige.py
- src/eva/vision/models/wrappers/from_registry.py
- src/eva/vision/models/wrappers/from_timm.py
Not all models will use tensors as input & output. E.g. models from other modalities such as `language` for instance would use `str` (prompt input -> generated text output) or `list[str]` (batch of input prompts).
Given that `BaseModel` is part of `eva.core`, ideally it should support multiple modalities, which this PR enables through generic type hints for the inputs & outputs of the forward pass.
Example model wrapper class definitions:
```python
class YourVisionModel(BaseModel[torch.Tensor, torch.Tensor]):
... 
class YourLanguageModel(BaseModel[list[str], list[str]]):
...
```
> Replace input/output type hints in `BaseModel` by type vars

- docs/user-guide/advanced/model_registry.md
- src/eva/core/utils/factory.py
- src/eva/core/utils/registry.py
- src/eva/vision/models/networks/backbones/__init__.py
- src/eva/vision/models/networks/backbones/pathology/bioptimus.py
- src/eva/vision/models/networks/backbones/pathology/gigapath.py
- src/eva/vision/models/networks/backbones/pathology/histai.py
- src/eva/vision/models/networks/backbones/pathology/hkust.py
- src/eva/vision/models/networks/backbones/pathology/kaiko.py
- src/eva/vision/models/networks/backbones/pathology/lunit.py
- src/eva/vision/models/networks/backbones/pathology/mahmood.py
- src/eva/vision/models/networks/backbones/pathology/owkin.py
- src/eva/vision/models/networks/backbones/pathology/paige.py
- src/eva/vision/models/networks/backbones/radiology/swin_unetr.py
- src/eva/vision/models/networks/backbones/radiology/voco.py
- src/eva/vision/models/networks/backbones/registry.py
- src/eva/vision/models/networks/backbones/timm/backbones.py
- src/eva/vision/models/networks/backbones/universal/vit.py
- src/eva/vision/models/wrappers/from_registry.py
- tests/eva/core/utils/test_factory.py
- tests/eva/vision/models/networks/backbones/test_registry.py
- Refactors the `BackboneModelRegistry` class into a more generic `Registry` class and moves the logic from `eva.vision` to `eva.core`
- The new `Registry` class now supports both classes & methods (previously only methods were supported)
- Adds a `Factory` class to do the class instantiation there instead of in the registry
With this change we can now easily add registries for different things (e.g. data transforms):
```python
from eva.core.utils.registry import Registry
transforms_registry = Registry()
```
> Refactor `Registry` class and move to `eva.core`

- pdm.lock
- pyproject.toml
Previous requirement was too tight as `language` pipeline also seems to work with older versions.
> Change datasets requirement to `datasets<4.0.0,>=2.19.0`

- src/eva/core/data/dataloaders/dataloader.py
Current logic in this case wrongly assigns `multiprocessing.cpu_count()` instead of `0` to `num_workers`
> Fix case where number of dataloader workers is 0

- src/eva/multimodal/models/wrappers/huggingface.py
E.g. for fine tuned models where `self.model_name_or_path` is set to the checkpoint path, the processor we still might want to load from the original model source.
> Make processor source configurable through `processor_kwargs` in `HuggingFaceModel`

- src/eva/multimodal/models/networks/others.py
- src/eva/multimodal/models/wrappers/huggingface.py
PR to make the `image` keyword for multimodal processors configurable, which can differ between models (most commonly `image`, e.g., Qwen-2.5VL, and `images`, e.g., Patho-R1, MedGemma)
> Make image input kwarg in multimodal processor configurable
