docs/index.md, mkdocs.yml
- starting page renamed to "Introduction"
- expand dropdowns by default
=> update documentation layout

.github/workflows/docs.yaml
=> Rename docs deploy

README.md, pyproject.toml
=> Bump version to `0.0.1`

renovate.json
Lifecycle management improvements through Renovate
Closes #366
=> #366 additional Renovate settings

pdm.lock, pyproject.toml
closes https://github.com/kaiko-ai/eva/issues/370
=> Update `lightning` to version `2.2.2`

src/eva/vision/data/datasets/segmentation/base.py, src/eva/vision/data/datasets/segmentation/total_segmentator.py, tests/eva/vision/data/datasets/segmentation/test_total_segmentator.py
=> Update `TotalSegmentator` output binary masks to a semantic mask

src/eva/vision/data/datasets/segmentation/total_segmentator.py, src/eva/vision/utils/convert.py, tests/eva/vision/utils/test_convert.py
=> Add support for 8bit images in TotalSegmentator

src/eva/vision/utils/io/nifti.py
=> Add `read_nifti_slice` to optionally cast image to stored input type

.github/workflows/ci.yaml
=> Update CI triggering events

src/eva/core/models/modules/head.py
=> Move model freezing functionality to `configure_model`

configs/vision/dino_vit/offline/panda.yaml
updated panda config with split arguments in `WsiClassificationDataset`
=> fix: updated panda config

src/eva/core/models/modules/module.py
=> Move metrics to CPU when using single device

src/eva/vision/data/wsi/backends/__init__.py, src/eva/vision/data/wsi/backends/base.py, src/eva/vision/data/wsi/backends/openslide.py, src/eva/vision/data/wsi/backends/tiffslide.py, tests/eva/vision/data/datasets/test_wsi.py
=> Add `TiffSlide` backend

src/eva/vision/data/datasets/wsi.py, tests/eva/vision/data/datasets/classification/test_panda.py, tests/eva/vision/data/datasets/classification/test_wsi.py, tests/eva/vision/data/datasets/test_wsi.py
=> Move WSI initialization logic from `MultiWsiDataset.__init__` to `MultiWsiDataset.setup`

README.md
=> Update `README` with paper citation

README.md
=> Update img shields of README

pdm.lock, pyproject.toml
=> Fix `torch` and `jsonargparse` versions

README.md
=> Update paper citation

configs/vision/dino_vit/offline/bach.yaml, configs/vision/dino_vit/offline/crc.yaml, configs/vision/dino_vit/offline/mhist.yaml, configs/vision/dino_vit/offline/patch_camelyon.yaml, configs/vision/dino_vit/online/bach.yaml, configs/vision/dino_vit/online/crc.yaml, configs/vision/dino_vit/online/mhist.yaml, configs/vision/dino_vit/online/patch_camelyon.yaml, configs/vision/owkin/phikon/offline/bach.yaml, configs/vision/owkin/phikon/offline/crc.yaml, configs/vision/owkin/phikon/offline/mhist.yaml, configs/vision/owkin/phikon/offline/patch_camelyon.yaml, configs/vision/tests/offline/patch_camelyon.yaml, configs/vision/tests/online/patch_camelyon.yaml, src/eva/vision/data/datasets/classification/bach.py, src/eva/vision/data/datasets/classification/base.py, src/eva/vision/data/datasets/classification/crc.py, src/eva/vision/data/datasets/classification/mhist.py, src/eva/vision/data/datasets/classification/patch_camelyon.py, src/eva/vision/data/transforms/common/resize_and_crop.py, src/eva/vision/utils/io/__init__.py, src/eva/vision/utils/io/image.py, tests/eva/vision/data/datasets/classification/test_bach.py, tests/eva/vision/data/datasets/classification/test_crc.py, tests/eva/vision/data/datasets/classification/test_mhist.py, tests/eva/vision/data/datasets/classification/test_patch_camelyon.py, tests/eva/vision/data/transforms/common/test_resize_and_crop.py
=> Update the vision dataset return types to `tv_tensors`

src/eva/core/metrics/defaults/segmentation/multiclass.py, tests/eva/core/metrics/defaults/segmentation/test_multiclass.py
=> Fix default segmentation metrics

configs/vision/dino_vit/online/total_segmentator_2d.yaml, src/eva/vision/models/networks/decoders/segmentation/conv.py, src/eva/vision/models/networks/decoders/segmentation/linear.py, tests/eva/vision/models/networks/decoders/segmentation/conv.py, tests/eva/vision/models/networks/decoders/segmentation/linear.py
=> Add support for multi-level embeddings training in segmentation tasks

configs/vision/dino_vit/online/total_segmentator_2d.yaml, src/eva/vision/callbacks/loggers/batch/base.py, src/eva/vision/models/networks/encoders/from_timm.py
=> Fix SemanticSegmentationLogger callback write frequency

src/eva/vision/models/modules/semantic_segmentation.py
=> Minor fixes in `SemanticSegmentationModule`

configs/vision/dino_vit/offline/bach.yaml, configs/vision/dino_vit/offline/crc.yaml, configs/vision/dino_vit/offline/patch_camelyon.yaml, configs/vision/dino_vit/online/bach.yaml, configs/vision/dino_vit/online/crc.yaml, configs/vision/dino_vit/online/patch_camelyon.yaml, configs/vision/owkin/phikon/offline/bach.yaml, configs/vision/owkin/phikon/offline/crc.yaml, configs/vision/owkin/phikon/offline/patch_camelyon.yaml
=> Rename `DOWNLOAD` env var to `DOWNLOAD_DATA`

docs/datasets/camelyon16.md, docs/datasets/index.md, docs/datasets/panda.md, docs/index.md, docs/leaderboards.md, docs/user-guide/advanced/replicate_evaluations.md, mkdocs.yml
closes https://github.com/kaiko-ai/eva/issues/528
(Note: updated leaderboard results will follow in: https://github.com/kaiko-ai/eva/issues/532)
=> Updated documentation with new datasets and leaderboard

configs/vision/dino_vit/online/total_segmentator_2d.yaml, src/eva/vision/data/datasets/segmentation/__init__.py, src/eva/vision/data/datasets/segmentation/total_segmentator_2d.py, src/eva/vision/utils/io/text.py, tests/eva/assets/vision/datasets/total_segmentator/Totalsegmentator_dataset_v201/meta.csv, tests/eva/vision/data/datasets/segmentation/test_total_segmentator.py
=> Support the full `TotalSegmentator2D` dataset 

README.md, docs/leaderboards.md, docs/user-guide/advanced/replicate_evaluations.md, mkdocs.yml
closes https://github.com/kaiko-ai/eva/issues/532
=> 532 update leaderboard results with slide level tasks

src/eva/vision/data/datasets/classification/camelyon16.py, src/eva/vision/data/datasets/wsi.py, tests/eva/vision/data/datasets/classification/test_camelyon16.py
closes https://github.com/kaiko-ai/eva/issues/499
=> make sure multiwsidatasets are validated (updated)

configs/vision/dino_vit/online/consep.yaml, src/eva/vision/models/networks/encoders/__init__.py, src/eva/vision/models/networks/encoders/from_timm.py, src/eva/vision/models/networks/encoders/from_visiontransformer.py, src/eva/vision/models/networks/encoders/wrapper.py
closes https://github.com/kaiko-ai/eva/issues/550
=> `EncoderWrapper` model and fixes for segmentation tasks

configs/vision/dino_vit/online/consep.yaml, configs/vision/dino_vit/online/monusac.yaml, configs/vision/dino_vit/online/total_segmentator_2d.yaml, src/eva/vision/data/transforms/common/resize_and_clamp.py
=> Fix normalisation in `ResizeAndClamp` transform

src/eva/vision/models/networks/encoders/from_timm.py
=> Allow local checkpoint to be loaded in `TimmEncoder`

configs/vision/dino_vit/offline/bcss.yaml, configs/vision/dino_vit/offline/consep.yaml, configs/vision/dino_vit/offline/monusac.yaml, configs/vision/dino_vit/offline/total_segmentator_2d.yaml, configs/vision/dino_vit/online/bcss.yaml, configs/vision/dino_vit/online/consep.yaml, configs/vision/dino_vit/online/monusac.yaml, configs/vision/dino_vit/online/total_segmentator_2d.yaml, configs/vision/phikon/offline/consep.yaml, configs/vision/phikon/online/consep.yaml, pdm.lock, src/eva/core/metrics/__init__.py, src/eva/core/metrics/defaults/segmentation/multiclass.py, src/eva/core/metrics/generalized_dice.py, src/eva/core/metrics/mean_iou.py
=> Add `ignore_index` functionality in segmentation metrics

src/eva/vision/data/datasets/segmentation/lits.py
=> Fix LiTS dataset validation

src/eva/core/callbacks/writers/embeddings/segmentation.py
=> Fix the embeddings saving dataset

configs/vision/dino_vit/offline/lits.yaml
=> Remove `cpu` accelerator from `LiTS` config

configs/vision/dino_vit/offline/bcss.yaml, configs/vision/dino_vit/offline/consep.yaml, configs/vision/dino_vit/offline/lits.yaml, configs/vision/dino_vit/offline/monusac.yaml, configs/vision/dino_vit/offline/total_segmentator_2d.yaml, configs/vision/dino_vit/online/bcss.yaml, configs/vision/dino_vit/online/consep.yaml, configs/vision/dino_vit/online/lits.yaml, configs/vision/dino_vit/online/monusac.yaml, configs/vision/dino_vit/online/total_segmentator_2d.yaml, configs/vision/phikon/offline/consep.yaml, configs/vision/phikon/online/consep.yaml, pdm.lock, pyproject.toml, src/eva/vision/__init__.py, src/eva/vision/losses/__init__.py, src/eva/vision/losses/dice.py
Closes #586 
CoNSePT: orange (bad): cross entropy, orange (good): dice online, green: dice offline
=> Add `Dice` segmentation loss

src/eva/vision/losses/dice.py
=> 589 fix dice loss function for ignore index argument

configs/vision/dino_vit/offline/lits.yaml, configs/vision/dino_vit/online/lits.yaml
=> Fix `LiTS` transforms

docs/user-guide/advanced/replicate_evaluations.md, src/eva/vision/models/networks/backbones/pathology/__init__.py, src/eva/vision/models/networks/backbones/pathology/bioptimus.py, src/eva/vision/models/networks/backbones/pathology/lunit.py, src/eva/vision/models/networks/backbones/pathology/mahmood.py
=> Add `H-optimus-0` model to registry

docs/user-guide/advanced/replicate_evaluations.md, src/eva/core/models/transforms/extract_cls_features.py, src/eva/core/models/transforms/extract_patch_features.py, src/eva/core/models/wrappers/huggingface.py, src/eva/vision/callbacks/loggers/batch/segmentation.py, src/eva/vision/models/networks/backbones/_utils.py, src/eva/vision/models/networks/backbones/pathology/__init__.py, src/eva/vision/models/networks/backbones/pathology/histai.py, src/eva/vision/models/networks/backbones/pathology/kaiko.py, src/eva/vision/models/networks/backbones/pathology/lunit.py, src/eva/vision/models/networks/backbones/pathology/mahmood.py, src/eva/vision/models/networks/backbones/pathology/owkin.py, src/eva/vision/models/networks/backbones/universal/timm.py, src/eva/vision/models/networks/backbones/universal/vit.py
=> Add `hibou` models to registry

configs/vision/radiology/offline/segmentation/lits.yaml, src/eva/core/callbacks/writers/embeddings/base.py, src/eva/core/utils/memory.py
=> Copy metadata entries to CPU in embeddings writer

configs/vision/pathology/offline/classification/bach.yaml, configs/vision/pathology/offline/classification/crc.yaml, configs/vision/pathology/offline/classification/mhist.yaml, configs/vision/pathology/offline/classification/panda.yaml, configs/vision/pathology/offline/classification/patch_camelyon.yaml, configs/vision/pathology/offline/segmentation/bcss.yaml, configs/vision/pathology/offline/segmentation/consep.yaml, configs/vision/pathology/offline/segmentation/monusac.yaml, configs/vision/pathology/offline/segmentation/total_segmentator_2d.yaml, configs/vision/pathology/online/classification/bach.yaml, configs/vision/pathology/online/classification/crc.yaml, configs/vision/pathology/online/classification/mhist.yaml, configs/vision/pathology/online/classification/patch_camelyon.yaml, configs/vision/pathology/online/segmentation/bcss.yaml, configs/vision/pathology/online/segmentation/consep.yaml, configs/vision/pathology/online/segmentation/monusac.yaml, configs/vision/pathology/online/segmentation/total_segmentator_2d.yaml, configs/vision/radiology/offline/segmentation/lits.yaml, configs/vision/radiology/online/segmentation/lits.yaml
=> Make dataset root fully configurable through env variable

src/eva/vision/callbacks/loggers/batch/segmentation.py
=> Update segmentation visualisation default arguments to show one column per group

configs/vision/pathology/offline/segmentation/consep.yaml, configs/vision/pathology/online/segmentation/consep.yaml, src/eva/vision/data/datasets/segmentation/consep.py
`num_classes ` was set to `8` but it's `5`.
=> Corrected number of classes in `CoNSeP` configs

src/eva/vision/models/networks/backbones/timm/backbones.py
=> Remove `dynamic_img_size` from `timm/{timm_model}` registry function

pyproject.toml
=> bump to 0.1.0

configs/vision/pathology/offline/segmentation/consep.yaml, configs/vision/pathology/online/segmentation/consep.yaml, src/eva/vision/data/datasets/segmentation/consep.py
=> Use `GridSampler` for `CoNSeP`

configs/vision/pathology/offline/classification/bach.yaml, configs/vision/pathology/offline/classification/camelyon16.yaml, configs/vision/pathology/offline/classification/crc.yaml, configs/vision/pathology/offline/classification/mhist.yaml, configs/vision/pathology/offline/classification/panda.yaml, configs/vision/pathology/offline/classification/patch_camelyon.yaml, configs/vision/pathology/offline/segmentation/bcss.yaml, configs/vision/pathology/offline/segmentation/consep.yaml, configs/vision/pathology/offline/segmentation/monusac.yaml, configs/vision/pathology/offline/segmentation/total_segmentator_2d.yaml, configs/vision/pathology/online/classification/bach.yaml, configs/vision/pathology/online/classification/crc.yaml, configs/vision/pathology/online/classification/mhist.yaml, configs/vision/pathology/online/classification/patch_camelyon.yaml, configs/vision/pathology/online/segmentation/bcss.yaml, configs/vision/pathology/online/segmentation/consep.yaml, configs/vision/pathology/online/segmentation/monusac.yaml, configs/vision/pathology/online/segmentation/total_segmentator_2d.yaml, configs/vision/radiology/offline/segmentation/lits.yaml, configs/vision/radiology/online/segmentation/lits.yaml, docs/user-guide/getting-started/how_to_use.md, src/eva/core/utils/progress_bar.py, src/eva/vision/data/datasets/segmentation/monusac.py, src/eva/vision/data/datasets/segmentation/total_segmentator_2d.py
=> Make `tqdm` progress bar configurable through `TQDM_REFRESH_RATE` env variable

src/eva/vision/data/datasets/segmentation/lits.py, src/eva/vision/utils/io/__init__.py, src/eva/vision/utils/io/nifti.py
=> Add option to `LiTS` to adjust orientation

docs/DEVELOPER_GUIDE.md, pdm.toml
=> Update developer guide & `pdm.toml`

docs/user-guide/advanced/replicate_evaluations.md, src/eva/core/models/transforms/extract_cls_features.py, src/eva/core/models/transforms/extract_patch_features.py, src/eva/vision/models/networks/backbones/_utils.py, src/eva/vision/models/networks/backbones/pathology/__init__.py, src/eva/vision/models/networks/backbones/pathology/histai.py, src/eva/vision/models/networks/backbones/pathology/mahmood.py, src/eva/vision/models/networks/backbones/pathology/paige.py, tests/eva/core/models/wrappers/test_huggingface.py
=> Add Virchow2 model to registry

pdm.lock, pyproject.toml, src/eva/vision/utils/io/nifti.py
=> Relax `nibabel` version dependency

pdm.lock, pyproject.toml
=> Update `nibabel` depedency

docs/user-guide/advanced/replicate_evaluations.md, src/eva/vision/models/networks/backbones/pathology/mahmood.py
=> Add `UNI2-h` model to registry

src/eva/core/models/modules/head.py
=> Update head module documentation

src/eva/vision/models/networks/backbones/pathology/mahmood.py
Closes #755
Apparently they changed the download instructions on https://huggingface.co/MahmoodLab/UNI
=> Update `UNI` download logic

configs/vision/pathology/offline/classification/gleason_arvaniti.yaml, configs/vision/pathology/online/classification/gleason_arvaniti.yaml, docs/datasets/gleason_arvaniti.md, docs/datasets/gleason_arvanti.md, docs/datasets/index.md, mkdocs.yml, src/eva/vision/data/datasets/__init__.py, src/eva/vision/data/datasets/classification/__init__.py, src/eva/vision/data/datasets/classification/gleason_arvaniti.py, tests/eva/assets/vision/datasets/arvaniti_gleason_patches/test_patches_750/patho_1/ZT80_38_A_1_2/ZT80_38_A_1_2_patch_18_class_1.jpg, tests/eva/assets/vision/datasets/arvaniti_gleason_patches/train_validation_patches_750/ZT111_4_B_4_6/ZT111_4_B_4_6_patch_12_class_1.jpg, tests/eva/assets/vision/datasets/arvaniti_gleason_patches/train_validation_patches_750/ZT204_6_B_7_8/ZT204_6_B_7_8_patch_3_class_2.jpg, tests/eva/assets/vision/datasets/arvaniti_gleason_patches/train_validation_patches_750/ZT76_39_A_1_2/ZT76_39_A_1_2_patch_00_class_0.jpg, tests/eva/vision/data/datasets/classification/test_gleason_arvaniti.py, tests/eva/vision/test_vision_cli.py
=> Add `GleasonArvaniti` dataset

configs/vision/pathology/offline/segmentation/monusac.yaml, configs/vision/radiology/offline/segmentation/total_segmentator_2d.yaml, configs/vision/radiology/online/segmentation/lits.yaml, configs/vision/radiology/online/segmentation/lits_balanced.yaml
In some configs this was set to 1
=> Change default number of runs to 5

configs/vision/pathology/offline/classification/bracs.yaml, configs/vision/pathology/offline/classification/breakhis.yaml, configs/vision/pathology/offline/classification/crc.yaml, configs/vision/pathology/offline/classification/gleason_arvaniti.yaml, configs/vision/pathology/offline/classification/unitopatho.yaml, configs/vision/pathology/online/classification/bracs.yaml, configs/vision/pathology/online/classification/breakhis.yaml, configs/vision/pathology/online/classification/crc.yaml, configs/vision/pathology/online/classification/gleason_arvaniti.yaml, configs/vision/pathology/online/classification/unitopatho.yaml, configs/vision/pathology/online/segmentation/monusac.yaml, docs/user-guide/getting-started/how_to_use.md
=> Add `RESIZE_DIM` parameter to `yaml` configs where it was missing

docs/user-guide/advanced/replicate_evaluations.md, src/eva/vision/models/networks/backbones/pathology/__init__.py, src/eva/vision/models/networks/backbones/pathology/kaiko.py
=> Add `Midnight-12k` to model registry

pdm.lock, pyproject.toml, src/eva/core/models/wrappers/_utils.py, src/eva/vision/models/networks/backbones/__init__.py, src/eva/vision/models/networks/backbones/radiology/__init__.py, src/eva/vision/models/networks/backbones/radiology/swin_unetr.py, src/eva/vision/models/networks/backbones/radiology/voco.py, src/eva/vision/models/networks/decoders/segmentation/__init__.py, src/eva/vision/models/networks/decoders/segmentation/linear.py, src/eva/vision/models/networks/decoders/segmentation/semantic/__init__.py, src/eva/vision/models/networks/decoders/segmentation/semantic/swin_unetr.py, tests/eva/vision/models/networks/backbones/radiology/test_swin_unetr.py, tests/eva/vision/models/networks/decoders/segmentation/test_conv.py, tests/eva/vision/models/networks/decoders/segmentation/test_linear.py, tests/eva/vision/models/networks/decoders/segmentation/test_swin_unetr.py
Closes #797
Credits to @ioangatop, I mainly ported the code he has written here.
=> Add `VoCo` to model registry

configs/vision/radiology/online/segmentation/2d/btcv.yaml, configs/vision/radiology/online/segmentation/2d/lits17.yaml, configs/vision/radiology/online/segmentation/2d/msd_task7_pancreas.yaml, src/eva/vision/models/networks/backbones/universal/__init__.py, src/eva/vision/models/networks/backbones/universal/vit.py
- BTCV & MSD configs were missing for 2D
- Added ViT-B model (makes more sense to use this instead of ViT-S as baseline model)
=> Add `2D` radiology configs

src/eva/language/models/wrappers/litellm.py
=> Enable `litellm.drop_params` in `LiteLLMModel`

src/eva/core/data/samplers/classification/balanced.py
Makes the `BalancedSampler` compatible with `str` inputs by adding a conditional check
=> Make `BalancedSampler` compatible with str inputs for language and multimodal
